baseURL = "https://storywith.in/"
title = "æ¯å¤©ä¸€ä¸ªè„‘æ´æ•…äº‹â€¦â€¦"
paginate = 12
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
hasCJKLanguage = true
rssLimit = 10
pygmentsUseClasses = true

[permalinks]
posts = "/:sections/:year/:month/:slug"

[minify]
disableXML = true
minifyOutput = true

[params]
social = true
env = "production"
title = "æ¯å¤©ä¸€ä¸ªè„‘æ´æ•…äº‹â€¦â€¦"
description = "æ¯å¤©è®°å½•ä¸€ä¸ªAIåˆ›ä½œçš„å°æ•…äº‹"
keywords = [
  "AI",
  "è„‘æ´æ•…äº‹",
  "å†™ä½œ",
  "åˆ›æ„",
  "äººå·¥æ™ºèƒ½",
  "åšå®¢",
  "ChatGPT",
  "Claude",
  "æ–‡å­¦",
  "æ•…äº‹"
]
author = "Me"
images = [ "story_twitter_card.png" ]
DateFormat = "January 2, 2006"
defaultTheme = "light"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false
mainSections = [ "post", "posts", "blog" ]

  [params.assets]
  favicon = "story_logo.png"
  favicon16x16 = "story_logo.png"
  favicon32x32 = "story_logo.png"
  apple_touch_icon = "story_logo.png"
  safari_pinned_tab = "story_logo.png"

  [params.label]
  text = "Home"
  icon = ""
  iconHeight = 35

  [params.homeInfoParams]
  Title = "äººç±»ï¼Œä½ å¥½ ğŸ‘‹"
  Content = "è¿™é‡Œæ˜¯åŸºäºäººå·¥æ™ºèƒ½çš„æ•…äº‹åšå®¢ï¼Œç®—åŠ›å…è®¸çš„æƒ…å†µä¸‹ï¼Œæ¯ä¸€å¤©è¯•ç€åˆ›é€ ä¸€ä¸ªå°æ•…äº‹â€¦â€¦æœ¬åšå®¢å†…å®¹ä¸å«äººç±»æˆåˆ†ï¼Œçº¯ç¡…åŸºç”Ÿå‘½æ’°å†™ã€‚"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/iamshaynez"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true
  image = "story_twitter_card.png"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
weight = 5

[[menu.main]]
identifier = "categories"
name = "åˆ†ç±»"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "search"
name = "æœç´¢"
url = "/search/"
weight = 15

[[menu.main]]
identifier = "tags"
name = "æ ‡ç­¾"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "author"
name = "æˆ‘æ˜¯è°"
url = "https://xiaowenz.com"
weight = 30

[markup.highlight]
noClasses = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[sitemap]
changefreq = "always"
filename = "sitemap.xml"
priority = 0.5
